drop table Project353.Users;

create table Project353.Users(

USERID    	VARCHAR(25),
PASSWORD    VARCHAR(64),
FIRSTNAME   VARCHAR(25),
LASTNAME    VARCHAR(25),
EMAIL       VARCHAR(25),
PROFILEURL	varchar(50),
MAJOR		VARCHAR(25),
UNIVERSITY	VARCHAR(25),

ACT   		INTEGER,
SAT			INTEGER	


);
