drop table Project353.Users;

create table Project353.Users(

USERID    			VARCHAR(25),
PASSWORD    		VARCHAR(64),
FIRSTNAME   		VARCHAR(25),
LASTNAME    		VARCHAR(25),
EMAIL       		VARCHAR(25),
PROFILEURL			VARCHAR(50),
FOLLOWING			VARCHAR(1000),
GRADDETAILS			VARCHAR(50),
HIGHSCHOOLDETAILS	VARCHAR(200),
ACT   				INTEGER,
SAT					INTEGER	


);
